Fix kwargs in crf_decode_forward
tensorflow/addons pull request #2642
Opened 2021-12-30 17:56 UTC by tgsmith61591

# Description

* Addresses issue #2639 by adding the `zero_output_for_mask=True` arg in `crf_decode_forward`
* Adds two new tests to show the mask is properly applied

## Type of change

- [x] Bug fix

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [x] By running Black + Flake8
    - [ ] By running pre-commit hooks
- [x] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

# How Has This Been Tested?

* Test to show that when a mask is applied, masked positions are equal to zero
* Test to show that when masking is *not* applied, no positions are equal to zero

2022-01-05 16:32 UTC, howl-anderson commented
Hi @tgsmith61591, I will take a closer look into this PR in the next few days.

2022-01-13 18:35 UTC, tgsmith61591 commented
Hi @howl-anderson any chance you've gotten to take a look at this? Thanks!

2022-01-13 18:50 UTC, howl-anderson commented
Hi @tgsmith61591, I am working on it, I will finish the PR review ASAP.

2022-01-19 07:35 UTC, howl-anderson requested changes
LGTM, we can merge this PR after @tgsmith61591 make the change according to the comment.

2022-01-19 07:35 UTC, howl-anderson commented on tensorflow_addons/text/tests/crf_test.py
> +    backpointers, last_score = text.crf_decode_forward(
Since the variable `last_score` is not used in the context. The standard way to handle it is to name this variable `_`.

2022-01-19 19:15 UTC, tgsmith61591 commented
Done @howl-anderson thanks!

2022-01-20 02:03 UTC, howl-anderson approved these changes
LGTM

2022-01-21 00:12 UTC, seanpmorgan approved these changes

2022-01-21 01:25 UTC, merged